name: nu_parent
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0  
  google_fonts: ^6.1.0
  intl_phone_field: ^3.1.0
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  google_sign_in: ^6.2.0
  fluttertoast: ^8.2.4
  flutter_countdown_timer: ^4.1.0
  flutter_ringtone_player: ^3.2.0
  shared_preferences: ^2.2.2
  flutter_custom_dialog: ^1.3.0
  flutter_tts: ^3.8.5
  video_player: ^2.8.1
  chewie: ^1.7.4
  liquid_pull_to_refresh: ^3.0.1
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sansation
      fonts:
        - asset: fonts/Sansation_Regular.ttf
